export const diseasesList = [
  "Diabetes",
  "Hypertension",
  "Hypotension",
  "Arthritis",
  "Osteoporosis",
  "Asthma",
  "Chronic Bronchitis",
  "Sinusitis",
  "Migraine",
  "Anxiety Disorder",
  "Depression",
  "Insomnia",
  "Obesity",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Acne",
  "Psoriasis",
  "Eczema",
  "Hair Loss (Alopecia)",
  "Dandruff",
  "Constipation",
  "Diarrhea",
  "Irritable Bowel Syndrome (IBS)",
  "Gastritis",
  "Acid Reflux (GERD)",
  "Ulcer",
  "Piles (Hemorrhoids)",
  "Fissures",
  "Urinary Tract Infection (UTI)",
  "Kidney Stones",
  "Fatty Liver",
  "Liver Cirrhosis",
  "High Cholesterol",
  "Anemia",
  "PCOS/PCOD",
  "Menstrual Disorders",
  "Infertility",
  "Erectile Dysfunction",
  "Premature Ejaculation",
  "Low Immunity",
  "Cold & Flu",
  "Cough (Dry/Wet)",
  "Tuberculosis (supportive care)",
  "Joint Pain",
  "Back Pain",
  "Sciatica",
  "Spondylitis",
  "Varicose Veins",
  "Skin Allergies",
  "Eye Strain / Computer Vision Syndrome",
];
